feat: add poetry, ruff, mypy
hj-eunice/InterviewBoost-API pull request #2
Opened 2024-02-09 12:24 UTC by JUNGYU-RIM1

Add poetry ruff mypy

Formatting code

Add types for removing mypy error

2024-02-10 00:07 UTC, hj-eunice requested changes

2024-02-10 00:07 UTC, hj-eunice commented on README.md
> +poetry run gunicorn app:app -b :8000 --chdir src
looks like Poetry chooses Python 3.12 by default, no matter what Python version a system uses. For those who use lower versions of Python, (for example I've been using 3.10.12) a few steps are needed before `poetry run`:

(`MY_PY_VER` is a placeholder for the python version like 3.10)
1. edit `python` in `tool.poetry.dependencies` in pyproject.toml. ex: `python = "^MY_PY_VER"`
2. run `poetry env use MY_PY_VER`

Can you please add these lines to README?

2024-02-10 00:14 UTC, hj-eunice commented on README.md
> +poetry run gunicorn app:app -b :8000 --chdir src
or we could fix the min pyhon to=^3.8 or higher.

2024-02-10 04:04 UTC, hj-eunice submitted a review, later dismissed

2024-02-10 08:51 UTC, JUNGYU-RIM1 commented on README.md
> +poetry run gunicorn app:app -b :8000 --chdir src
> or we could fix the min python to=^3.8 or higher.

Fix using python 3.8 or higher
But we should use a fixed python version anyway. discuss it Friday's sync

2024-02-17 00:57 UTC, hj-eunice approved these changes

2024-02-17 01:18 UTC, merged